// AQUI VAMOS IMPLEMENTAR A FUNCAO QUE VAI PEGAR OS DADOS DAS TABELAS
// VAMOS RECEBER COMO PARAMETRO QUAL VAI SER DADO (ex getJsonData.php?data=energia )
// E DAREMOS COMO RETORNO UM JSON COM OS DADOS

<?php

  include 'db.php';


?>
